### PR TITLE
Updating compose to version 3

### PR DESCRIPTION
**Pull request by isuftin**
- Updated the Docker compose configuration to version 3
- Set up Docker volumes for the Docker containers in the Docker compose config
- Set up a Docker network in Docker compose
- Added CHANGELOG
- Updated README with changes made

### CODE REVIEW

**Comment by julienchastang** [comment]
@isuftin Can you explain to me how the `volumes` and `networks` are supposed to work in practice? Also should we have done this for `thredds-docker` or did I miss this? Typically, I use the local file system as the intermediary between containers for file/data persistence. How does all this work in docker-compose version 3?

**Comment by isuftin** [comment]
With networks, docker-compose creates a named network for the Docker containers. What this allows is for inter-container communication without you, the deployer, having to worry about networking the containers together. The containers know each other by the network alias you set on the container in compose. By doing this, the TDM container (for example) doesn't need to know the actual IP address of the Thredds container. It can just make calls to "thredds" as the address. If you look in the hosts file on TDM, you will notice that Docker has added the thredds fqdn and put an IP to it. That IP is the thredds container. This is very convenient in order to network containers that work together. Along with this, you don't have to worry about ports being opened between containers. If you don't explicitly map a port in compose for a container, other containers can still access other container ports while on the same Docker network. Things like this can really be appreciated when Docker Swarm comes into play and you begin clustering containers.

With volumes, what compose does is create a Docker volume container that mounts to a given location in the container. Early on in Docker, if you wanted to maintain permanency for your data and you didn't want to or couldn't mount your host filepath, you'd manually create a Docker container that served only to hold data. You'd use one of the smallest Docker images you could find (Alpine or busybox usually) and have it run something like "echo 1" in order to come up and exit immediately. This exited container was then able to be mounted to another container via the file system. This allowed you to have a somewhat permanent storage location for data in a container. Kind of cool, but annoying to do in practice. Docker then came out with volumes which did the same thing but as a first-class process. So in this compose file, we create a docker volume to mount into thredds. I added this here in place of fake paths so that a user may be able to just run `docker-compose up` without having to do any edits to the compose config and be up and running immediately. This, of course, is optional but seemed to be a cleaner configuration to me. Ultimately, a user will want to mount their host filesystem to the thredds container or to the volume container but when you first grab this project, I didn't want to make any assumptions so I just end up creating a volume instead.

**Comment by isuftin** [comment]
I think that for this standalone container, there's probably no need to put it on a network so we can probably remove that.

For the volume, I'd suggest either keeping the volume ceration in there for default launching or just keep this line in there commented out: https://github.com/Unidata/tdm-docker/pull/5/files#diff-4e5e90c6228fd48698d074241c2ba760R16

**Comment by julienchastang** [comment]
Thanks for the discussion. I think what I'm going to do is split this apart as I usually like to do:

  1. Simply move to version 3 and nothing else (i.e., not take advantage of the aforementioned features) (#3) 
  2. Externalize environment variables (#11). We know how to do this now.
  3. Incorporate docker-compose version 3 volumes and whatnot. (No specific issue for this yet.)

**Comment by isuftin** [comment]
@julienchastang I think that works.

**Comment by julienchastang** [comment]
closed by #12

**Comment by julienchastang** [comment]
And what I meant to say, is now that we have migrated to dc v3, we can tackle the network and volume issues. Do you mind opening an issue for whatever you think is necessary in this area? Thanks.

**Pull request closed without merging**
